### ISSUE TITLE
DisconnectError

### ISSUE THREAD

**Issue by RDaneelOlivav** [jpieper/pygazebo#33]
Why and how to handle this? I realy don't know why this happens and what could be done to solve this?

ERROR:trollius:Exception in callback <lambda>(<Future ...tError()>) at /home/ubuntu/pygazebo/pygazebo/pygazebo.py:659
handle: <Handle <lambda>(<Future ...tError()>) at /home/ubuntu/pygazebo/pygazebo/pygazebo.py:659>
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/trollius-1.0.4-py2.7.egg/trollius/events.py", line 151, in _run
    self._callback(*self._args)
  File "/home/ubuntu/pygazebo/pygazebo/pygazebo.py", line 659, in <lambda>
    lambda future: self._handle_server_data(future, connection))
  File "/home/ubuntu/pygazebo/pygazebo/pygazebo.py", line 662, in _handle_server_data
    message = future.result()
  File "/usr/local/lib/python2.7/dist-packages/trollius-1.0.4-py2.7.egg/trollius/futures.py", line 287, in result
    raise self._exception
DisconnectError

**Comment by MalinAan** [comment]
Did you figure this out? I have the same issue.
